name: Godot CI/CD Pipeline

on: [push, pull_request]

env:
  GODOT_VERSION: "4.2.1"
  GODOT_STATUS: "stable"
jobs:
  import-assets:
    runs-on: ubuntu-latest
    container: barichello/godot-ci:4.2.1
    steps:
      - uses: actions/checkout@v4
      - name: Cache import assets
        uses: actions/cache@v3
        with:
          path: .godot/imported/
          key: import-assets-${{ runner.os }}-${{ github.sha }}
      - name: Import assets
        run: godot --headless --verbose --editor --quit

  export-game:
    runs-on: ubuntu-latest
    needs: import-assets
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v3
        with:
          path: .godot/imported/
          key: import-assets-${{ runner.os }}-${{ github.sha }}
      - name: install wine
        run: |
          sudo apt install wine64
          echo "WINE_PATH=$(which wine64)" >> $GITHUB_ENV
      - name: Export Game using Godot
        uses: firebelley/godot-export@v5.2.1
        with:
          godot_executable_download_url: "https://github.com/godotengine/godot/releases/download/${{ env.GODOT_VERSION }}-${{ env.GODOT_STATUS }}/Godot_v${{ env.GODOT_VERSION }}-${{ env.GODOT_STATUS }}_linux.x86_64.zip"
          godot_export_templates_download_url: "https://github.com/godotengine/godot/releases/download/${{ env.GODOT_VERSION }}-${{ env.GODOT_STATUS }}/Godot_v${{ env.GODOT_VERSION }}-${{ env.GODOT_STATUS }}_export_templates.tpz"
          relative_project_path: "./godot"
          archive_output: true
          cache: false
          wine_path: ${{ env.WINE_PATH }}
      - name: Upload HTML5
        uses: actions/upload-artifact@v4
        with:
          name: HTML5
          path: /home/runner/.local/share/godot/archives/HTML5.zip
      - name: Upload Linux
        uses: actions/upload-artifact@v4
        with:
          name: LinuxX11
          path: /home/runner/.local/share/godot/archives/LinuxX11.zip
      - name: Upload Windows
        uses: actions/upload-artifact@v4
        with:
          name: Windows
          path: /home/runner/.local/share/godot/archives/Windows.zip
      - name: Upload MacOS
        uses: actions/upload-artifact@v4
        with:
          name: macOS
          path: /home/runner/.local/share/godot/archives/macOS.zip

  deploy-to-itchio-linux:
    runs-on: ubuntu-latest
    needs: export-game
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: LinuxX11
      - name: Deploy to Itch.io (Windows)
        uses: manleydev/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_API_KEY }}
          CHANNEL: linux
          ITCH_GAME: ${{ secrets.ITCHIO_GAME }}
          ITCH_USER: ${{ secrets.ITCHIO_USERNAME }}
          PACKAGE: LinuxX11.zip

  deploy-to-itchio-windows:
    runs-on: ubuntu-latest
    needs: export-game
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: Windows
      - name: Deploy to Itch.io (Windows)
        uses: manleydev/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_API_KEY }}
          CHANNEL: windows
          ITCH_GAME: ${{ secrets.ITCHIO_GAME }}
          ITCH_USER: ${{ secrets.ITCHIO_USERNAME }}
          PACKAGE: Windows.zip

  deploy-to-itchio-mac:
    runs-on: ubuntu-latest
    needs: export-game
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: macOS
      - name: Deploy to Itch.io (MacOS)
        uses: manleydev/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_API_KEY }}
          CHANNEL: mac
          ITCH_GAME: ${{ secrets.ITCHIO_GAME }}
          ITCH_USER: ${{ secrets.ITCHIO_USERNAME }}
          PACKAGE: macOS.zip

  deploy-to-itchio-web:
    runs-on: ubuntu-latest
    needs: export-game
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: HTML5
      - name: Deploy to Itch.io (HTML5)
        uses: manleydev/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_API_KEY }}
          CHANNEL: web
          ITCH_GAME: ${{ secrets.ITCHIO_GAME }}
          ITCH_USER: ${{ secrets.ITCHIO_USERNAME }}
          PACKAGE: HTML5.zip
