name: Godot CI/CD Pipeline

on: [push, pull_request]

env:
  EXPORT_NAME: the-last-seed

jobs:
  import-assets:
    runs-on: ubuntu-latest
    container: barichello/godot-ci:4.2.1
    steps:
      - uses: actions/checkout@v2
      - name: Cache import assets
        uses: actions/cache@v2
        with:
          path: .godot/imported/
          key: import-assets-${{ runner.os }}-${{ github.sha }}
      - name: Import assets
        run: godot --headless --verbose --editor --quit

  export-linux:
    runs-on: ubuntu-latest
    container: barichello/godot-ci:4.2.1
    needs: import-assets
    steps:
      - uses: actions/checkout@v2
      - name: Export for Linux
        run: |
          mkdir -v -p build/linux
          cd godot/
          godot --headless --verbose --export-release "Linux/X11" ../build/linux/$EXPORT_NAME.x86_64
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ env.EXPORT_NAME }}-linux
          path: build/linux

  export-windows:
    runs-on: ubuntu-latest
    container: barichello/godot-ci:4.2.1
    needs: import-assets
    steps:
      - uses: actions/checkout@v2
      - name: Export for Windows
        run: |
          mkdir -v -p build/windows
          cd godot/
          godot --headless --verbose --export-release "Windows Desktop" ../build/windows/$EXPORT_NAME.exe
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ env.EXPORT_NAME }}-windows
          path: build/windows

  export-mac:
    runs-on: ubuntu-latest
    container: barichello/godot-ci:4.2.1
    needs: import-assets
    steps:
      - uses: actions/checkout@v2
      - name: Export for Mac
        run: |
          mkdir -v -p build/mac
          cd godot/
          godot --headless --verbose --export-release "Mac OSX" ../build/mac/$EXPORT_NAME.zip
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ env.EXPORT_NAME }}-mac
          path: build/mac

  export-web:
    runs-on: ubuntu-latest
    container: barichello/godot-ci:4.2.1
    needs: import-assets
    steps:
      - uses: actions/checkout@v2
      - name: Export for Web/HTML5
        run: |
          mkdir -v -p build/web
          cd godot/
          godot --headless --verbose --export-release "HTML5" ../build/web/index.html
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ env.EXPORT_NAME }}-web
          path: build/web

  deploy-to-itchio-linux:
    runs-on: ubuntu-latest
    needs: export-linux
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: ${{ env.EXPORT_NAME }}-linux
          path: build/linux
      - name: Deploy to Itch.io (Linux)
        run: butler push build/linux ${{ secrets.ITCHIO_USERNAME }}/${{ secrets.ITCHIO_GAME }}:linux
        env:
          BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}

  deploy-to-itchio-windows:
    runs-on: ubuntu-latest
    needs: export-windows
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: ${{ env.EXPORT_NAME }}-windows
          path: build/windows
      - name: Deploy to Itch.io (Windows)
        run: butler push build/windows ${{ secrets.ITCHIO_USERNAME }}/${{ secrets.ITCHIO_GAME }}:windows
        env:
          BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}

  deploy-to-itchio-mac:
    runs-on: ubuntu-latest
    needs: export-mac
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: ${{ env.EXPORT_NAME }}-mac
          path: build/mac
      - name: Deploy to Itch.io (Mac)
        run: butler push build/mac ${{ secrets.ITCHIO_USERNAME }}/${{ secrets.ITCHIO_GAME }}:mac
        env:
          BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}

  deploy-to-itchio-web:
    runs-on: ubuntu-latest
    needs: export-web
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: ${{ env.EXPORT_NAME }}-web
          path: build/web
      - name: Deploy to Itch.io (Web)
        run: butler push build/web ${{ secrets.ITCHIO_USERNAME }}/${{ secrets.ITCHIO_GAME }}:web
        env:
          BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
